-- MySQL Script generated by MySQL Workbench
-- Thu Feb  5 13:17:30 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema backend-project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema backend-project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `backend-project` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `backend-project` ;

-- -----------------------------------------------------
-- Table `backend-project`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend-project`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `backend-project`.`boards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend-project`.`boards` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `description` LONGTEXT NULL,
  `author` VARCHAR(255) NULL,
  `likes` INT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_boards_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_boards_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `backend-project`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `backend-project`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend-project`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `backend-project`.`boards_has_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend-project`.`boards_has_categories` (
  `boards_id` INT NOT NULL,
  `categories_id` INT NOT NULL,
  PRIMARY KEY (`boards_id`, `categories_id`),
  INDEX `fk_boards_has_categories_categories1_idx` (`categories_id` ASC),
  INDEX `fk_boards_has_categories_boards1_idx` (`boards_id` ASC),
  CONSTRAINT `fk_boards_has_categories_boards1`
    FOREIGN KEY (`boards_id`)
    REFERENCES `backend-project`.`boards` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_boards_has_categories_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `backend-project`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `backend-project`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend-project`.`comments` (
  `id` INT NOT NULL,
  `content` LONGTEXT NULL,
  `author` VARCHAR(255) NULL,
  `date` DATETIME NULL,
  `board_id` INT NOT NULL,
  PRIMARY KEY (`id`, `board_id`),
  INDEX `fk_comments_boards1_idx` (`board_id` ASC),
  CONSTRAINT `fk_comments_boards1`
    FOREIGN KEY (`board_id`)
    REFERENCES `backend-project`.`boards` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
